// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW78jJN0rGjaRXIolSEBKiPmFdD3Ah0Qw',
    appId: '1:639325301190:web:a6243c3680e1e3783f2ac7',
    messagingSenderId: '639325301190',
    projectId: 'notes-task-app',
    authDomain: 'notes-task-app.firebaseapp.com',
    storageBucket: 'notes-task-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-nowOIlx-xtp1QIpT2TwvQIHJRGcUqXk',
    appId: '1:639325301190:android:f0348c3277cd44553f2ac7',
    messagingSenderId: '639325301190',
    projectId: 'notes-task-app',
    storageBucket: 'notes-task-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCusHje3NFy8SuxQ9yRi5o_o7wZdNaLfcc',
    appId: '1:639325301190:ios:ec107297c437b3873f2ac7',
    messagingSenderId: '639325301190',
    projectId: 'notes-task-app',
    storageBucket: 'notes-task-app.firebasestorage.app',
    iosBundleId: 'com.example.notesTaskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCusHje3NFy8SuxQ9yRi5o_o7wZdNaLfcc',
    appId: '1:639325301190:ios:ec107297c437b3873f2ac7',
    messagingSenderId: '639325301190',
    projectId: 'notes-task-app',
    storageBucket: 'notes-task-app.firebasestorage.app',
    iosBundleId: 'com.example.notesTaskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW78jJN0rGjaRXIolSEBKiPmFdD3Ah0Qw',
    appId: '1:639325301190:web:61a0498ed6e41ea33f2ac7',
    messagingSenderId: '639325301190',
    projectId: 'notes-task-app',
    authDomain: 'notes-task-app.firebaseapp.com',
    storageBucket: 'notes-task-app.firebasestorage.app',
  );
}
